# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# seed inital user
User.delete_all
User.create(name: 'admin', username: 'admin', password: 'admin', password_confirmation: 'admin')

# seed pages
Page.delete_all
Page.create(title: 'Consulting for Retailers', url_title: 'retailers', page_type: 'consulting', :seo_description: '', seo_keywords: '', content: '')

# seed bios
Bio.delete_all
Bio.create(name: 'Burt Flickinger',content: '<p>Widely known and recognized as a leading expert on all aspects of the supermarket wholesaling and retailing industry, Burt has worked as a consultant for top retail chains around the globe. His family has been in the wholesale, vertically and horizontally integrated private label production, manufacturing, and branding businesses for four generations since his great grandfather founded S.M. Flickinger Company &ndash; the largest supermarket wholesaler/retailer headquartered in the eastern U.S. prior to its acquisition by Metro Haniel Europe, the owner of Scrivner. The Flickingers and FMI, National Association of Wholesale Grocers (NAWGA), and Food Distribution Institute (FDI) had a partnership across four generations in the horizontal and vertical development of Federated Foods (which the Flickinger family founded) full line private label brands. Burt, his father, grandfather, and great grandfather worked in partnership with the Fleming, Nash, Finch, Albertsons, and other regional co-op families and corporations.</p>
<p>Prior to founding Strategic Resource Group, Burt&rsquo;s extensive career included working for S.M. Flickinger in buying, merchandising, marketing, operations, warehousing, transportation, private label development, and real estate, Procter &amp; Gamble, Glendinning Associates, Interpublic, and serving as Director of Price Waterhouse Coopers/Management Horizons Marketing: Wholesaling, and Retailing Consulting Practice. For years, Burt was a contributing editor and featured monthly &ldquo;Flickinger File&rdquo; columnist for Progressive Grocer. Also, he was contributing industry editor of both Global Retail Insights and Supermarket Insights. Burt and the Flickinger family, along with Cornell&rsquo;s Food Industry Management program and Private Label Magazine, co-published The Future of Private Label in North America.</p>')

Bio.create(name: 'Richard Rehn', content: '<p>Rick has premier executive level retail &amp; wholesale credit management experience, and he has served as a financial risk management consultant to leading Fortune 500 companies nationwide. Rick worked for Procter &amp; Gamble (the #1 supplier to U.S. supermarkets, co-ops &amp; wholesalers) for thirty years, where he served as Credit Manager, North America, for P&amp;G&rsquo;s retail and wholesale customers. He served as Chairman and as a member of numerous Unsecured Creditor Committees (including Furr&rsquo;s Supermarkets, Appletree Supermarkets, Harvest Food Supermarkets, Revco, Pharmor, etc.). He is Vice Chairman of the National Association of (retail chains) Credit Managers and Director of the Credit (retail) Research Foundation. Rick has testified as an expert on retail finance in several court cases. Rick had the entire Procter &amp; Gamble credit group report to him. His group analyzed the credit conditions and financial viability of individual family owned and operated stores to Gulf Coast region bankruptcies, e.g., Bruno&rsquo;s, Jitney Jungle- Delchamp&rsquo;s, Fleming and Winn Dixie, et al. He is an established expert in analyzing credit of retailers from a single store, small family owned and operated supermarket chains, and large publicly held retail chains. Rick holds an MBA in Finance from Xavier University, and he is a graduate of the National Association of Credit Management Graduate School of Credit &amp; Financial Management. Also, Rick is a Certified Credit Expert (CCE) National Association of Credit Management, and he is Certified Expert Witness (CEW) of the National Association of Credit Management. Rick is a Colonel in the U.S. Army Reserves, retired.</p>')

Bio.create(name: 'Martin Roberts', content: '<p>Martin is a widely recognized retail store design industry expert with outstanding retail store design (and configuration) credentials in the United States and across the globe. Martin has designed some of the most innovative and successful retail formats both nationally and internationally. Martin is a member of The Institute of Store Planners and The Society of Industrial Designers, and The Royal Society of Arts (London). Martin&rsquo;s design work is included in the permanent collection of the Museum of Modern Art in New York.</p>')

Bio.create(name: 'Molly Ford', content: '<p>Molly is a leading authority in branding, advertising, and efficient consumer targeting. Also, Ms. Ford has a depth and range of experience in new media, social networking to traditional broadcast (radio and TV), print (magazines &amp; news) and online marketing. Molly was a founding officer of Disney Infoseek, as well as AOL, and was Chief Integration Officer of Netscape. Molly was the highest ranking business woman executive at US News &amp; World Report, Business Week and Time. She was a leading executive at Time Warner and led executive teams in many consumer related businesses. Ms. Ford started her career in her family&rsquo;s international multi-format retailing and distribution businesses. She has served on the boards of various educational, philanthropic and business institutions.</p>')

Bio.create(name: 'Sturgess Spanos', content: '<p>Sturgess has over 25 years experience in classic food distribution, &quot;on premise&quot; gourmet, specialty, and traditional food &amp; beverage businesses. Sturgess was Operating Partner at JSS/Old Yankee Beverage, the largest fine wine &amp; spirit distributor &amp; retailer in Northern New England. He was National Sales Manager for Fossil Farms&rsquo; specialty gourmet meats and national &amp; international fresh products portfolio. As National Accounts Manager for San Pelligrino, Pana &amp; Nestle Waters, he helped establish these brands as leaders in the &ldquo;on premise&rdquo;, retail, wholesale, food service &amp; consumer sales categories.</p>
<p>Throughout his career, Sturgess has worked with some the best distributors, retailers, wholesalers, restaurants, and consumer brand companies across the globe. Sturgess has also worked with a broad range of SRG clients, including: Agri Beef, Ahold USA, U.S. Foodservice &amp; due diligence work for various private equity firms, on Kings, et al.</p>')

Bio.create(name: 'Henry Mellet', content: '<p>Henry is a Senior Consultant with SRG and has done extensive research on retail chains across all channels. Henry has worked with the leading co-ops, wholesalers, retail chains, brand manufacturers, and financial institutions in the industry, as well as the Federal Trade Commission (FTC). He is proficient in due diligence investigation and in-depth retail research and analysis. Mr. Mellet is a graduate of the University of Texas and joined SRG in 1998.</p>')

Bio.create(name: 'Paul D. Bauer', content: '<p>Paul is currently on the Board of Directors of the Selective Insurance Group (NASDAQ:SIGI), a $1.6 billion property and casualty insurance underwriter and serves as the Chairman of the Salary and Benefits Committee; he was former Chair of the Audit Committee. He is also on the Board of Rosina Holdings, a food processor and Fluent Energy, an energy consulting firm. He was formerly on the Board of Advisors of Ciminelli Development Company, a developer of commercial real estate in the Eastern United States and Canada. </p>
<p>Paul was Executive Vice President and Chief Financial Officer of Tops Markets, Inc., from 1970-1993. Tops at the time was a $1.2billion operator and franchisor of retail food supermarkets. His responsibilities included all accounting, SEC and financial areas, including lease negotiations, investor relations, franchisee relations, information services and technology, non-food purchasing and strategic planning for the company. During his tenure, the company was a public company twice, did two management-led buyouts and sold to Royal Ahold in 1991. Paul began his career at KPMG. </p>
<p>Paul is currently a co-founder (1995) and President of the BISON Fund, a private scholarship fund that provides financial assistance to economically challenged families so that their children can attend private elementary school instead of failing inner-city and Buffalo area public schools. He is a former trustee of the Foundation of the Diocese of Buffalo, D&rsquo;youville College, Canisius High School, Holy Angels Academy, the Catholic Health system and the YMCA . He has received an honorary Doctorate from D&rsquo;Youville College, the Gaudete Medal from St. Bonaventure University and is a Knight of the Holy Sepulcher. He graduated from Boston College.</p>')

Bio.create(name: 'Henry Mellet', content: 'Leif has an undergraduate & Masters Degree in Engineering & Quantitative Analysis from Cornell University.  Leif has done engineering analyses, as well as market & shopping center analyses in acquisition and FTC matters.')

Bio.create(name: 'Nick Donald', content: '<p>Nick is a 2011 graduate from Princeton University with a focus in geographic informational systems. Nick has assisted in consulting and litigation matters in a number of capacities. Using large databases from both federal and private sources, he has provided analyses for use in marketing consultation and litigation. Nick is also a web developer and has created website mock-ups for prospective clients. He also developed the SRG website on the front- and back-ends.</p>')

Bio.create(name: 'Leif Ericksen', content: '<p>Leif has an undergraduate & Masters Degree in Engineering & Quantitative Analysis from Cornell University.  Leif has done engineering analyses, as well as market & shopping center analyses in acquisition and FTC matters.</p>')

Bio.create(name: 'Juliana Rogers', content: '<p>Juliana has performed extensive analyses and research of both chain and franchisee sector businesses.  Juliana has in-depth experience in market analysis & competitive compression modeling and is a graduate of Cornell University.</p>')